name: CI/CD Workflow

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login localhost:5600 \
            -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Build & push image
        run: |
          docker build -t localhost:5600/bakagott-intern-next:latest .
          docker push localhost:5600/bakagott-intern-next:latest

      - name: Chech status
        run: echo "🍏 This job's status is ${{ job.status }}."