name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login gitea.yourdomain.local \
            -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Build & push image
        run: |
          docker build -t gitea.yourdomain.local/bakagott-intern-next:latest .
          docker push gitea.yourdomain.local/bakagott-intern-next:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/bakagott-intern-next
            docker compose pull
            docker compose up -d